export const RETRIEVE_PROPERTIES_FULFILLED = "RETRIEVE_PROPERTIES_FULFILLED";
export const RETRIEVE_PROPERTIES_REJECTED = "RETRIEVE_PROPERTIES_REJECTED";
export const SAVE_OR_UPDATE_FULFILLED = "SAVE_OR_UPDATE_FULFILLED";
export const SAVE_OR_UPDATE_REJECTED = "SAVE_OR_UPDATE_REJECTED";
export const REQUEST_DEPARTED = "REQUEST_DEPARTED";
export const REQUEST_ARRIVED = "REQUEST_ARRIVED";
export const CLEAR_SAVE_FLAG = "CLEAR_SAVE_FLAG";
